services:
  - type: web
    name: Companies_sector_research
    env: python
    plan: free
    buildCommand: |
      cd Company_growth_data_clustering_project/backend
      pip install -r requirements.txt
    startCommand: |
      cd Company_growth_data_clustering_project/backend
      gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "10000"
